services:
  backend:
    image: controle-financeiro-api
    build:
      context: ./webapi/src/
      dockerfile: ControleFinanceiro.Infrastructure/dockerfile
    ports:
      - "8081:8080"
    networks:
      - controle-financeiro
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__Database: Host=${DB_HOST};Port=${DB_PORT};Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}
      FRONTEND_URL: http://frontend:8080

  frontend:
    build:
      context: ./frontend/
      args:
          VITE_API_URL: /api
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - controle-financeiro

  db:
    image: postgres
    container_name: controle-financeiro-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ControleFinanceiro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - controle-financeiro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ControleFinanceiro" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  controle-financeiro:
    driver: bridge
